#!/bin/sh

# Assumptions:
# Mail file structure is like the following for all accounts with no exceptions:
# $mailRoot/$accountId/{Inbox, Archive}

main() {
    threadFiles=$(notmuch search --output=files thread:$1 | grep -E '/(Inbox|Archive)/')

    ensureUnambiguousThread "$threadFiles"

    accountRoot="$(realpath $(echo "$threadFiles" | head -1 | xargs dirname)/../..)"

    targetDir=$(echo "$threadFiles" | grep -q Inbox && echo Archive || echo Inbox)

    moveTo="$accountRoot/$targetDir/cur"

    set -e

    echo "$threadFiles" | while read f; do
        targetNameUIDStripped=$(basename $f | sed 's/,U=[0-9]\+//')

        cmd="mv $f $moveTo/$targetNameUIDStripped"

        test "$2" = "--dry-run" && echo $cmd || $cmd
    done

    test "$2" != "--dry-run" && notmuch new
}

ensureUnambiguousThread() {
    # For the corner case in which a thread belongs to multiple accounts, which
    # happens when a mail is sent from a local account to another. Notmuch can't
    # detect on which account we want to toggle the thread, so this script can't
    # handle it automatically and shifts the responsibility to the user instead.

    threadFiles="$1"

    echo "$threadFiles" \
    | xargs dirname \
    | reverseCut -d/ -f3- \
    | uniq \
    | wc -l \
    | xargs -I% test % -gt 1 \
    && echo Ambiguous thread, handle manually. Matched thread files: >&2 \
    && echo "" >&2 \
    && echo "$threadFiles" >&2 \
    && exit 1
}

reverseCut() { rev | cut "$@" | rev; }

main "$@"
